<?php

namespace common\models;

use common\components\StaticFunctions;
use Yii;

/**
 * This is the model class for table "post_image".
 *
 * @property int $id
 * @property int $post_id
 * @property int $type
 * @property string $image
 */
class PostImage extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post_image';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['post_id', 'type', 'image'], 'required'],
            [['post_id', 'type'], 'integer'],
            [['image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'post_id' => 'Post ID',
            'type' => 'Type',
            'image' => 'Image',
        ];
    }

    public function beforeDelete()
    {
        StaticFunctions::deleteImage($this->image, $this->post_id,'news');
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
